#pragma once

#define WORKSPACE1 "WORKSPACE1"
#define INFIREFOX1 "INFIREFOXY1"
#define INFIREFOX2 "INFIREFOXY2"
#define INBLUESCREEN "BLUESCREEN"
#define WORKSPACE2 "WORKSPACE2"
#define SETTINGS1 "INSETTINGS1"
#define WINDOWSFIREWALL1 "INWINDOWSFIREWALL1"
#define WINDOWSDEFENDERVIRUS1 "INWINDOWSDEFENDERVIRUS1"
#define WINDOWSDEFENDER1 "INWINDOWSDEFENDER1"
#define RANSOMWERE_MENU "RANSOMWERE_MENU"
#define SEGURANCA_DISPOSITIVO_MENU "SEGURANCA_DISPOSITIVO_MENU"
#define PROTECAO_CONTAS_MENU "PROTECAO_CONTAS_MENU"
#define OPCOES_FAMILIA_MENU "OPCOES_FAMILIA_MENU"

